<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Nama Lencana_target_point</name>
   <tag></tag>
   <elementGuidId>8344ab18-890e-4d4c-ad67-886435c064a3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='floating_outlined_input_:rd:']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7238cdd4-a29f-4299-8f6e-72e21f845f63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>1eaa2bef-0e79-41a3-90ec-544d06ab610c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>floating_outlined_input_:rd:</value>
      <webElementGuid>f1d687de-d0ef-48ee-a4b3-5aa28a94d607</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>block px-4 py-4 w-full text-sm text-gray-900 bg-transparent rounded-lg border border-[#949494] appearance-none focus:outline-none focus:ring-0 focus:border-blue-600 peer</value>
      <webElementGuid>1ed1fe4a-f668-43bb-9e61-515b3ed66e41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>bb95bb3c-60c6-4af8-91b2-4dcd02edbf95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>target_point</value>
      <webElementGuid>49c8a72b-b169-4af4-b544-ac4a6e7450ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>150000</value>
      <webElementGuid>1278bbda-f55e-43d5-8ed4-60445d8977b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;floating_outlined_input_:rd:&quot;)</value>
      <webElementGuid>e2a30eba-cb86-470b-ae72-fac8deed9261</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='floating_outlined_input_:rd:']</value>
      <webElementGuid>2d07c498-a6ff-474b-b3cc-c1af6630cec4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='chakra-modal--body-:r7:']/div/div[2]/div/input</value>
      <webElementGuid>2a22678e-307f-45fc-ab0a-898401a78833</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>c18afd25-9817-4af4-bd64-4d72a54c060c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @id = 'floating_outlined_input_:rd:' and @name = 'target_point']</value>
      <webElementGuid>013cabdb-b8dd-42df-ab48-4ca75a5b8a1f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
