<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Tolak-Approval Misi</name>
   <tag></tag>
   <elementGuidId>28d28957-7b26-412c-bafc-521328f1896e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='menu-button-:rac:']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>983c46fb-2617-4a25-b177-1745153312be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>9c650fa3-687a-4974-864d-c846827a7adf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>chakra-button chakra-menu__menu-button css-cb0v6o</value>
      <webElementGuid>b26e8e3d-8ba7-45db-8dce-575caa114baa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>menu-button-:rac:</value>
      <webElementGuid>d07cce79-41ab-4d6e-807c-9d922efa0c71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>13f509e6-ec4a-48d2-b140-c38d10ce9ecd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>menu</value>
      <webElementGuid>a71f95eb-3113-42a7-b08b-9e080e5ed607</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>menu-list-:rac:</value>
      <webElementGuid>3c40949d-30b7-456b-b1a5-3810534912c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Tolak</value>
      <webElementGuid>6e3466d8-fafa-4262-ad8c-cf64fa50fcd3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu-button-:rac:&quot;)</value>
      <webElementGuid>d1edcec5-8566-4252-8374-2a01dfb854c4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='menu-button-:rac:']</value>
      <webElementGuid>a7004dbd-00ec-46d9-8526-5ca838746e32</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div[2]/section/div/div[2]/table/tbody/tr[2]/td[7]/div/button[2]</value>
      <webElementGuid>b482822b-af65-4be1-8fbb-0f76d67e6726</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Setujui'])[2]/following::button[1]</value>
      <webElementGuid>d86398a6-9e93-426d-8410-53efadb1a128</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='perlu tinjauan'])[2]/following::button[3]</value>
      <webElementGuid>4a6f35a8-ec11-48c4-8c0d-b081d8270a79</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bukti tidak jelas'])[2]/preceding::button[1]</value>
      <webElementGuid>fb876e58-06f7-4c93-8120-0b44a4e09d2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[7]/div/button[2]</value>
      <webElementGuid>fc381118-ea95-4ad7-adf6-a3e921c1b977</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'menu-button-:rac:' and (text() = 'Tolak' or . = 'Tolak')]</value>
      <webElementGuid>95931fe5-04e6-4404-8b36-c26b5c927f18</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
