<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Kembali-View-Approval Misi-Tinjauan</name>
   <tag></tag>
   <elementGuidId>8e2971a7-deb5-4ffc-a841-b4df31ba6659</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.chakra-button.css-9gry80</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[74]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>13f41bae-b90e-4be6-a8d4-63527284272e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>78fd5f88-eb6a-4b2c-944c-ae6d2c6beb76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>chakra-button css-9gry80</value>
      <webElementGuid>3e8e3f47-6575-4844-8fc9-9e3c8a0a97a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Kembali</value>
      <webElementGuid>18170a58-2723-45c8-b0f9-a13827ffbd4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;chakra-modal-:ra3:&quot;)/footer[@class=&quot;chakra-modal__footer css-jat8py&quot;]/button[@class=&quot;chakra-button css-9gry80&quot;]</value>
      <webElementGuid>281ed065-ac75-4304-b5ff-d2ed65735dd4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[74]</value>
      <webElementGuid>37284084-6f96-4689-83cd-7dabf44bd547</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='chakra-modal-:ra3:']/footer/button</value>
      <webElementGuid>5e658b99-6a38-4df3-80a5-12bd72712ebd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bukti pengerjaan'])[1]/following::button[2]</value>
      <webElementGuid>b98f0d67-0991-47f6-9ef6-0d77a3c1b1a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='`'])[2]/following::button[3]</value>
      <webElementGuid>b69c0cfc-66da-4802-918c-92760d0f28c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Kembali']/parent::*</value>
      <webElementGuid>0e8959fd-e75e-4340-a16e-023e8f2428c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//footer/button</value>
      <webElementGuid>97338fd2-b1a5-48e8-aa0f-7e182c3496b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Kembali' or . = 'Kembali')]</value>
      <webElementGuid>e722707f-e890-4867-acf3-95ef7d1738dd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
