<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Batal-Setuju</name>
   <tag></tag>
   <elementGuidId>10c1fd37-cd96-4ad5-9117-d44e335d71e9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.chakra-button.css-11nrecm</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[42]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>542bcfd1-9444-445d-a252-10323ec287a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>2e391a7d-b57a-4491-a38d-6b17a6cd0c86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>chakra-button css-11nrecm</value>
      <webElementGuid>522e4c33-76ba-401f-8af1-ab2a7d58df7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Batal</value>
      <webElementGuid>22d3ef9d-9ba1-4393-9934-d3caa4d0ecde</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;chakra-modal-:r4g:&quot;)/footer[@class=&quot;chakra-modal__footer css-8nkqp1&quot;]/button[@class=&quot;chakra-button css-11nrecm&quot;]</value>
      <webElementGuid>485d5dfc-727d-4954-8106-02f8bae589a3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[42]</value>
      <webElementGuid>664e2210-a3f8-4d54-94e1-6628458d3429</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='chakra-modal-:r4g:']/footer/button</value>
      <webElementGuid>e691735e-8b44-4331-b32a-6df073a5e942</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='`'])[2]/following::button[1]</value>
      <webElementGuid>349aa832-eca8-486d-a911-29ea033a7c7e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Alt'])[2]/following::button[1]</value>
      <webElementGuid>4f60285b-eccc-4d8b-8f3b-d128699ffb1b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Verifikasi'])[1]/preceding::button[1]</value>
      <webElementGuid>c5d2038d-a900-4526-b733-f243c5606175</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Batal']/parent::*</value>
      <webElementGuid>72bd8b01-1c3f-4d4f-8b3e-baa0de0bd522</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//footer/button</value>
      <webElementGuid>f380a9c7-b4b6-4823-a654-f67a12426dfe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Batal' or . = 'Batal')]</value>
      <webElementGuid>aebb0daa-f3e4-4ddf-9a1a-d7a08eeede84</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
