<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_ditolak-verify</name>
   <tag></tag>
   <elementGuidId>db5e8b87-ffc0-4c67-9611-6627ce1110b9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.chakra-badge.css-1u15ttx</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='chakra-modal--body-:r72:']/div/div[3]/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>ea82ddb1-4df3-452c-b781-e185f95333fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>chakra-badge css-1u15ttx</value>
      <webElementGuid>ef49ce5e-1ebb-40cd-8598-6e9bd74b8d4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ditolak</value>
      <webElementGuid>f6d6e1c6-c60e-4814-bf0f-4668a48f3edd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;chakra-modal--body-:r72:&quot;)/div[@class=&quot;css-1gbo05p&quot;]/div[@class=&quot;css-1lawy5a&quot;]/span[@class=&quot;chakra-badge css-1u15ttx&quot;]</value>
      <webElementGuid>7c5ea746-f8e8-461d-88c2-34445d58a86a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='chakra-modal--body-:r72:']/div/div[3]/span</value>
      <webElementGuid>e815650f-578f-42cc-990e-3a44325e2388</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PS-426DBB66343740D'])[2]/following::span[3]</value>
      <webElementGuid>b0c13307-a99d-46ee-a638-6b2cb645f5a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kembali'])[1]/preceding::span[1]</value>
      <webElementGuid>827f28a7-5d52-4e9d-b08e-56448585572d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/span</value>
      <webElementGuid>8cbfb2a6-8510-4631-ae5b-07293a4829cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'ditolak' or . = 'ditolak')]</value>
      <webElementGuid>131d4bcf-699d-450c-b041-7c75603c3e3f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
