<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_diterima-verify</name>
   <tag></tag>
   <elementGuidId>c72cae1d-485b-44c2-bd98-3f1af1b2abeb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.chakra-badge.css-gfmnx0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='chakra-modal--body-:r6m:']/div/div[3]/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>767acb6d-7025-4806-aedb-f2c9e87e3e14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>chakra-badge css-gfmnx0</value>
      <webElementGuid>bca0cb29-b35c-42cd-9079-b6e06ca79407</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>diterima</value>
      <webElementGuid>a890202a-a77b-4078-9de0-f504eadb4327</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;chakra-modal--body-:r6m:&quot;)/div[@class=&quot;css-1gbo05p&quot;]/div[@class=&quot;css-1lawy5a&quot;]/span[@class=&quot;chakra-badge css-gfmnx0&quot;]</value>
      <webElementGuid>4db3654c-3097-4794-92af-383c26440682</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='chakra-modal--body-:r6m:']/div/div[3]/span</value>
      <webElementGuid>53b87d4c-dd6f-4e60-8e87-5c5a10ac8cf4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PS-32B43572BBC14AE'])[2]/following::span[3]</value>
      <webElementGuid>7fb725fe-10a7-4618-bfd7-d05806676205</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kembali'])[1]/preceding::span[1]</value>
      <webElementGuid>c9733c42-4547-4fab-9a9a-321e4502e1aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/span</value>
      <webElementGuid>7aa15036-7189-4ebb-b14f-cbc481dbc8d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'diterima' or . = 'diterima')]</value>
      <webElementGuid>340cd849-9e2a-493f-8c43-8caea4006bf0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
