<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Tambahkan Email_password</name>
   <tag></tag>
   <elementGuidId>0c9d2810-ae13-4ac5-8890-68240339f542</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='floating_outlined:r15:']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5faf2bd5-f920-4751-8708-5b6505508192</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>d4972a53-f39b-4e47-ab6c-7396fef6bcfc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>floating_outlined:r15:</value>
      <webElementGuid>d84e4802-5ef9-4108-b83c-7bcbf3340355</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>block pl-12 pr-2.5 py-4 w-full text-sm text-gray-900 bg-transparent rounded-lg border border-[#949494] appearance-none focus:outline-none focus:ring-0 focus:border-blue-600 peer</value>
      <webElementGuid>871a8291-437d-4b0c-b350-1c0f3afeef88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>927a5ac0-90df-458f-a08a-0826055c4e7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>6bbb267a-8ea2-4a1b-b8e9-6d8a67901a88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;floating_outlined:r15:&quot;)</value>
      <webElementGuid>1b95800b-44db-4694-a062-d81c2467cdc8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='floating_outlined:r15:']</value>
      <webElementGuid>7c8b1037-63e5-4acd-8dfb-8c7a7193b4de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='chakra-modal--body-:r8:']/div[4]/div/div/input</value>
      <webElementGuid>465e2750-b96e-45ad-b9b5-dbf635e227e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div[3]/div/section/form/div/div[4]/div/div/input</value>
      <webElementGuid>a3445813-ac75-44ea-b490-fe292967dadd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @id = 'floating_outlined:r15:' and @name = 'password']</value>
      <webElementGuid>7af8bfe7-de4c-49b6-8722-74ff557f1835</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
