<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Tambah_fullname</name>
   <tag></tag>
   <elementGuidId>2ce0f754-0795-406f-ad79-ab84895cd399</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='floating_outlined:r11:']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d7dbde31-82dd-4bb1-9e36-13ccab711f18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c05cf0a0-bfd7-4bca-bdde-049e5f20c926</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>floating_outlined:r11:</value>
      <webElementGuid>77bb5481-8481-45ae-8177-d189bf2d8216</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>block pl-12 pr-2.5 py-4 w-full text-sm text-gray-900 bg-transparent rounded-lg border border-[#949494] appearance-none focus:outline-none focus:ring-0 focus:border-blue-600 peer</value>
      <webElementGuid>c4473734-4258-4f70-a9a4-9431d80c8cd7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>16b5f33e-572e-40e2-b343-b676185a57be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>fullname</value>
      <webElementGuid>087eb1e1-b6eb-465e-b43d-1b183a24c423</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;floating_outlined:r11:&quot;)</value>
      <webElementGuid>95773645-4f73-4f77-8771-1d8e8ae1cddb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='floating_outlined:r11:']</value>
      <webElementGuid>56073de4-0cbe-49ba-9961-b4f14948fdb1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='chakra-modal--body-:r8:']/div[2]/div/input</value>
      <webElementGuid>46361952-ebc4-41bb-b89f-950afda216c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div[3]/div/section/form/div/div[2]/div/input</value>
      <webElementGuid>9d5a4d4e-76ba-4d0f-b7c4-592db7fd8adc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'floating_outlined:r11:' and @name = 'fullname']</value>
      <webElementGuid>08a6fb97-c5a3-4836-9604-5250e1f2ae40</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
