<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Batal_Tambah</name>
   <tag></tag>
   <elementGuidId>1fa89378-777e-4815-bba7-4c20cbb86c46</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.chakra-button.css-11nrecm</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[29]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>63c5157f-6dfb-44d1-bbc3-575fcc09fc00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>eee24c5a-6600-4ee3-979c-d2ad60658357</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>chakra-button css-11nrecm</value>
      <webElementGuid>eee4f8dd-6055-4419-ae62-ed391755b3b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Batal</value>
      <webElementGuid>7d7ae7c3-2fb8-4c94-ae3e-8a29a013ba72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;chakra-modal-:r7:&quot;)/form[1]/footer[@class=&quot;chakra-modal__footer css-1barvad&quot;]/button[@class=&quot;chakra-button css-11nrecm&quot;]</value>
      <webElementGuid>661ec57b-3a0f-4d04-b669-9799fc7c60fe</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[29]</value>
      <webElementGuid>d2861d52-5e50-49bf-aec9-1495f7a1ac20</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='chakra-modal-:r7:']/form/footer/button</value>
      <webElementGuid>d35d5092-efbf-471c-b333-d5b0f81d9d08</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tanggal Berakhir Voucher'])[1]/following::button[1]</value>
      <webElementGuid>9a3d677e-b10d-4fab-b2cc-8f199133ac00</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tanggal Mulai Voucher'])[1]/following::button[1]</value>
      <webElementGuid>a36de91b-f9e4-4486-817a-d9903277b353</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tambah Data'])[1]/preceding::button[1]</value>
      <webElementGuid>4fcdfdeb-5a9e-48aa-ad8f-028d42c92503</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Batal']/parent::*</value>
      <webElementGuid>588f72f2-0ecc-4c65-a427-9184b3d9717f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//footer/button</value>
      <webElementGuid>99eadfba-cb09-4c2a-88f0-b214cd975d22</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Batal' or . = 'Batal')]</value>
      <webElementGuid>7f79dab2-83a2-47bd-83de-acb7173dd440</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
