<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Ubah Data-edit-voucher</name>
   <tag></tag>
   <elementGuidId>665f3f80-0313-4397-8a77-79549510e81d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@type='submit']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.chakra-button.css-bk74al</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>fd65f114-5adb-4681-97e0-bcca90c31f85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>892a0242-5f22-4a4d-b9ff-ee72b65aa9df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>chakra-button css-bk74al</value>
      <webElementGuid>7d20986c-e664-4bdb-af48-b0e401c90682</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Ubah Data</value>
      <webElementGuid>5bcbc7a7-e1e6-4af7-86fc-14658e9ef6eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;chakra-modal-:ra:&quot;)/form[1]/footer[@class=&quot;chakra-modal__footer css-1barvad&quot;]/button[@class=&quot;chakra-button css-bk74al&quot;]</value>
      <webElementGuid>e162af7b-4efc-4cbe-bfef-22ec26f8712a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@type='submit']</value>
      <webElementGuid>6b2aaade-2087-40a1-a223-6d856b755fd1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='chakra-modal-:ra:']/form/footer/button[2]</value>
      <webElementGuid>2e304e26-5e79-4da1-a1ce-13337199df3f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Batal'])[1]/following::button[1]</value>
      <webElementGuid>49b6f4b0-e2b6-4c58-b254-eba0e75a61c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tanggal Berakhir Voucher'])[1]/following::button[3]</value>
      <webElementGuid>00bebb86-c6db-475d-95a3-6376a2ee9231</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Ubah Data']/parent::*</value>
      <webElementGuid>7933da2c-c7b0-4c76-8697-9bf5ec46c22a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//footer/button[2]</value>
      <webElementGuid>b64c8dc5-57b4-4e1a-9c81-75201b9b7ab5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and (text() = 'Ubah Data' or . = 'Ubah Data')]</value>
      <webElementGuid>cac92139-3490-49ba-8a5d-955958256449</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
