<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Batal_Delete</name>
   <tag></tag>
   <elementGuidId>f4a2ef76-af57-411a-b1f8-2d3240a77660</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.chakra-button.w-40.css-11nrecm</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[29]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>7437a652-bb16-4f28-9cd5-de5c8e572c78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>c9fb1270-cf26-4a73-8ce6-40f543842a1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>chakra-button w-40 css-11nrecm</value>
      <webElementGuid>1c369c80-e1bc-41c6-8519-60f786f7da3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Batal</value>
      <webElementGuid>f6a42f30-2960-4a91-a8b8-8eed222a872b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;chakra-modal-:r13:&quot;)/footer[@class=&quot;chakra-modal__footer css-8nkqp1&quot;]/button[@class=&quot;chakra-button w-40 css-11nrecm&quot;]</value>
      <webElementGuid>3b6b61da-bb2a-4b99-8f18-d26f19b7e490</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[29]</value>
      <webElementGuid>2d1c99e0-5bf3-440a-8fd6-5fdef7ce793a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='chakra-modal-:r13:']/footer/button</value>
      <webElementGuid>2d3751dd-1eb9-4767-b615-c6440add6c26</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='`'])[2]/following::button[1]</value>
      <webElementGuid>c4636572-2e3f-4e1f-8294-88bda333fbd1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Alt'])[2]/following::button[1]</value>
      <webElementGuid>4eeba0ad-c2d0-42b4-a8bb-37b084394c53</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hapus'])[1]/preceding::button[1]</value>
      <webElementGuid>1db5e920-ae76-4136-8171-5b69d73c05cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Batal']/parent::*</value>
      <webElementGuid>4a75b7fa-632e-49e8-961b-0a9283e150a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//footer/button</value>
      <webElementGuid>5ac67fb5-c82a-41b6-9aa7-2767ee02bb61</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Batal' or . = 'Batal')]</value>
      <webElementGuid>75b85196-9b55-453b-a989-f1d577ccc593</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
