<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Deskripsi-Voucher-To-Edit</name>
   <tag></tag>
   <elementGuidId>0436cd21-1dee-497a-a027-945df992c7fa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='floating_outlined_input_:r13:']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>cf4fbf39-10a0-4aa0-aed9-0c0fc92ca101</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>floating_outlined_input_:r13:</value>
      <webElementGuid>8a651294-9310-43ff-8eda-dfd53c306244</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>resize-none block px-4 py-4 w-full text-sm text-gray-900 bg-transparent rounded-lg border border-[#949494] appearance-none focus:outline-none focus:ring-0 focus:border-blue-600 peer</value>
      <webElementGuid>478fe178-6b83-4014-874e-d420ddb0788e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>3f3db4d4-4852-4ea6-b203-d01f48edc31a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>82c7d217-68d8-46d9-9118-5e131c60e648</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>description</value>
      <webElementGuid>8463dacf-3e83-4f6e-9d80-6f27060021b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Voucher Sepulsa bisa diintegrasikan ke Gopay.</value>
      <webElementGuid>6e32aae6-27c7-4313-9fb6-f720b9e09cb0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;floating_outlined_input_:r13:&quot;)</value>
      <webElementGuid>1403de97-8052-4d09-a183-14d4db13f48b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='floating_outlined_input_:r13:']</value>
      <webElementGuid>aa3b812c-27f5-44ce-a363-528efb58d3b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='chakra-modal--body-:ra:']/div[2]/div[3]/div/div/textarea</value>
      <webElementGuid>11c375fd-d049-41eb-8a51-32c0318f3567</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Poin Voucher'])[1]/following::textarea[1]</value>
      <webElementGuid>a381c991-0efb-448b-be59-811fb5ee3940</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nama Voucher'])[1]/following::textarea[1]</value>
      <webElementGuid>4dbd4b34-e35e-49fc-a024-f1dc9966e68b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Deskripsi Voucher'])[1]/preceding::textarea[1]</value>
      <webElementGuid>501383b0-e0d1-40f7-83ca-f378527ae609</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tanggal Mulai Voucher'])[1]/preceding::textarea[1]</value>
      <webElementGuid>066ac98f-ee32-4497-a6e2-27fe2c4b9340</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Voucher Sepulsa bisa diintegrasikan ke Gopay.']/parent::*</value>
      <webElementGuid>30633af9-8de2-4dd0-a24e-d646521f3382</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>12cb6543-eea1-4d37-9889-5365c04a5303</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'floating_outlined_input_:r13:' and @name = 'description' and (text() = 'Voucher Sepulsa bisa diintegrasikan ke Gopay.' or . = 'Voucher Sepulsa bisa diintegrasikan ke Gopay.')]</value>
      <webElementGuid>9091c08d-2878-47d3-a31c-67b5957f463c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
