<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h1_Daftar Transaksi Tukar Poin</name>
   <tag></tag>
   <elementGuidId>e8f2b39c-fc44-4516-a508-3cf476567fa4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>h1.chakra-heading.css-1gsb7mq</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div[2]/div[2]/section/h1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>99e699c7-1347-4f4d-9a35-955e572b7376</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>chakra-heading css-1gsb7mq</value>
      <webElementGuid>ab2351cc-4098-4220-b579-794d6da7c7f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Daftar Transaksi Tukar Poin</value>
      <webElementGuid>1e47e2fc-739d-4fff-a001-fbb9b10b67bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;flex&quot;]/div[@class=&quot;w-full ml-[312px]&quot;]/div[@class=&quot;mt-12 border&quot;]/section[@class=&quot;chakra-container css-1wv7j7a&quot;]/h1[@class=&quot;chakra-heading css-1gsb7mq&quot;]</value>
      <webElementGuid>a3b7d446-c7e6-45fd-a9f4-5dc80dfa1afe</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div[2]/section/h1</value>
      <webElementGuid>2c1c2246-a88a-40eb-a210-ad7227567246</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Daftar Transaksi Tukar Poin']/parent::*</value>
      <webElementGuid>944f2010-8ee1-481d-b7cb-77c8f40738a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h1</value>
      <webElementGuid>7227b7d9-fc9d-4769-a0d1-f4dee94f6a0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h1[(text() = 'Daftar Transaksi Tukar Poin' or . = 'Daftar Transaksi Tukar Poin')]</value>
      <webElementGuid>71748da4-03e1-4bb9-9ffb-fc0287ad8290</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
